name: Package binary with Tauri

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: songsnap-mobile/package-lock.json

      - name: Install Rust (Stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: cd songsnap-mobile && npm ci

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: songsnap-mobile
          tauriScript: 'npm run tauri'
          args: --verbose

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: SongSnap-${{ matrix.platform }}
          path: |
            songsnap-mobile/src-tauri/target/release/bundle/dmg/*.dmg
            songsnap-mobile/src-tauri/target/release/bundle/deb/*.deb
            songsnap-mobile/src-tauri/target/release/bundle/appimage/*.AppImage
            songsnap-mobile/src-tauri/target/release/bundle/msi/*.msi
            songsnap-mobile/src-tauri/target/release/bundle/nsis/*.exe

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          files: artifacts/**/*
          generate_release_notes: true 